Divided viewport
imodeljs/frontend-sample-showcase pull request #112
Opened 2020-10-22 20:20 UTC by Ellord207

2020-10-22 20:21 UTC, Ellord207 commented
There is an bug I found where, if you lock the clip and change the comparison type, the comparison does not change.

2020-10-22 20:35 UTC, pmconne approved these changes
I have only nitpicks, which I will spare you. Good readable example.

2020-10-22 23:35 UTC, williamkbentley approved these changes

2020-10-22 23:58 UTC, Josh-Schifter requested changes
The UI is inconsistent with the other samples.

- Looks like you are using the wrong selector component
- The spacing between the labels and the other components is wrong.is wrong.

2020-11-10 19:15 UTC, Josh-Schifter requested changes

2020-11-10 19:15 UTC, Josh-Schifter commented on src/frontend-samples/swiping-viewport/Divider.tsx
> +  constructor(props: DividerComponentProps, context: any) {
Remove the "context" argument.  The code editor in the showcase reports this as a "problem" at runtime.

2020-11-10 19:15 UTC, Josh-Schifter commented on src/frontend-samples/swiping-viewport/SwipingComparisonApp.tsx
> +} from "@bentley/imodeljs-frontend";
I think we should collapse each of these import statements into a single line.  At present, the imports take up an entire screen in the code editor at runtime.

2020-11-10 20:24 UTC, Josh-Schifter approved these changes

2020-11-10 21:01 UTC, merged