Transformation sample
imodeljs/frontend-sample-showcase pull request #256
Opened 2021-08-11 13:08 UTC by dustinlebsock

The TransformationsClient will NOT work until the api is release to APIM. Scheduled release date is 8/13/2021

2021-08-13 13:57 UTC, dsmailys commented on src/frontend-samples/transformations-sample/README.md
> +There are three API's used to create the transformed iModel based on a [View Definition](https://www.itwinjs.org/reference/imodeljs-backend/viewdefinitions/viewdefinition/). The first API and step, [
Let's update these with prod links: https://developer.bentley.com/apis/transformations/operations/filterbyviewdefinition/

2021-08-13 14:01 UTC, dsmailys commented on src/frontend-samples/transformations-sample/README.md
> +There are three API's used to create the transformed iModel based on a [View Definition](https://www.itwinjs.org/reference/imodeljs-backend/viewdefinitions/viewdefinition/). The first API and step, [
Maybe: "THere are three steps to create the transformed iModel based on a...."

2021-08-13 14:02 UTC, dsmailys commented on src/frontend-samples/transformations-sample/README.md
> +There are three API's used to create the transformed iModel based on a [View Definition](https://www.itwinjs.org/reference/imodeljs-backend/viewdefinitions/viewdefinition/). The first API and step, [
The first step is to create a transformation configuration....

2021-08-13 14:03 UTC, dsmailys commented on src/frontend-samples/transformations-sample/README.md
> +The second API, [Create Transformation](https://sbx-developer.bentley.com/api-groups/synchronization/apis/transformations/operations/create-transformation/) actually starts the transformation process
https://developer.bentley.com/apis/transformations/operations/create-transformation/

2021-08-13 14:03 UTC, dsmailys commented on src/frontend-samples/transformations-sample/README.md
> +The third API, [Get Transformation](https://sbx-developer.bentley.com/api-groups/synchronization/apis/transformations/operations/get-transformation/), gets an updated transformation status as the tra
https://developer.bentley.com/apis/transformations/operations/get-transformation/

2021-08-13 14:06 UTC, dsmailys commented on src/frontend-samples/transformations-sample/TransformationsClient.ts
> +export interface Transformation {
This dto changed in APIM a bit, check response dto here: https://developer.bentley.com/apis/transformations/operations/get-transformation/

2021-08-13 14:06 UTC, dsmailys commented on src/frontend-samples/transformations-sample/TransformationsClient.ts
> +    const url = `https://sbx-api.bentley.com/transformations/transformations/${transformationId}`;
https://api.bentley.com/transformations/{transformationId}

2021-08-13 14:14 UTC, dsmailys commented on src/frontend-samples/transformations-sample/walkthru.md
> +For more information on the three API's used to accomplish this feat, see:
on the API's used to accomplish

2021-08-13 14:14 UTC, dsmailys commented on src/frontend-samples/transformations-sample/walkthru.md
> +
let's update to prod (already available)

2021-08-13 14:17 UTC, dsmailys requested changes
Some changes in regards to wording and api links submitted

2021-08-19 20:20 UTC, BaoTon reviewed
There seems to be an overlap with the 2d transformations sample when I run it locally:

![image](https://user-images.githubusercontent.com/39310001/130138254-b82a0b56-36fd-483c-8481-1d908ad19b6a.png)

2021-08-19 20:20 UTC, BaoTon commented on src/frontend-samples/transformations-sample/README.md
> +THere are three steps to create the transformed iModel based on a [View Definition](https://www.itwinjs.org/reference/imodeljs-backend/viewdefinitions/viewdefinition/). The first step is to create a
```suggestion
There are three steps to create the transformed iModel based on a [View Definition](https://www.itwinjs.org/reference/imodeljs-backend/viewdefinitions/viewdefinition/). The first step is to create a transformation configuration, in this example a [FilterByViewDefinition](https://developer.bentley.com/apis/transformations/operations/filterbyviewdefinition/), which creates an association between source and target iModels with additional metadata to carry out the transformation. It does NOT start the transformation. 
```

2021-08-19 23:00 UTC, BaoTon approved these changes
LGTM

2021-08-20 00:16 UTC, merged